### ISSUE TITLE
Guest Lecturer (Cont) & Clerk's Cust. Service

### ISSUE THREAD

**Issue by porkbob** [Kyuuhachi/Inevitable-Zero#3] opened 2022-10-05 02:17 UTC
For the Guest Lecturer Continued quest, I ran into some different issues. They do seem like they'd be a bit more tricky to fix than the previous ones.

First off, when you originally enter the room before initiating the quest, Ken and Nana (Juna's siblings from the Kai version) will be sitting in the middle pew on the right. When Lloyd & co exit the room to prepare and reenter, Nana  is then missing, and Ken's sprite is overlayed on top of another student.

A couple lines during the lecture are shown as coming from Ken but they are instead attributed to "Boy"—the lines being "Woah that's kinda cool!" and later "So cool...!" Nana does have a line attributed to her by name as well: "Lloyd... He's kinda cool..." but the text box points to I think the girl Ken is overlapping which is not using Nana's sprite.

Lastly, after the quest concludes and Sister Marble walks away, the game hangs before exiting the cutscene. I didn't exactly pay attention to how long, but it was 1-2 minutes probably. I thought it crashed, and I'm sure others will too and will quit out before control is regained.

As far as the Clerk's Customer Service quest, I didn't notice any issue, unless Tio's portrait is supposed to actually be shown in a different outfit during that scene when you show the Purrfect outfit to the waitress.

**Comment by Kyuuhachi** [comment] 2022-10-05 04:40
Hm, interesting. I suppose that'll be because I'm just copypasting the script right off from the vita, where K&N do not exist. That one'll need some manual intervention.

For CCS, there's supposed to be a full-body portrait for a short while, but the field sprite and chathead are unaffected.

**Comment by porkbob** [comment] 2022-10-05 04:47
I didn't see the full body portrait FWIW

**Comment by Kyuuhachi** [comment] 2022-10-05 04:50
Right, I'll look into it. Might take a while to get Guest Lecturer untangled... (If you're curious, the portrait is [this](https://steamuserimages-a.akamaihd.net/ugc/1785138296073867136/E9195977506C9D9246D49920F305C676DF74414D/).)

**Comment by porkbob** [comment] 2022-10-05 04:58
Yeah I kinda figured it was the thumbnail you used on Steam, which is the only reason I was expecting something, lol.

**Comment by Kyuuhachi** [comment] 2022-10-05 06:58
...Yeah this is totally broken. Wow.

I've managed to fix the misattributed dialogue and freezes, but currently K&N just sit quietly at their desk without participating at all, which is kind of awkward. So for that to work out satisfactorily I would need to brew up scripts for them from scratch...

For the portrait the problem is that the image straight up doesn't exist. An easy fix... I thought, but the one in the Vita data is low-res and the one in GF is a png. I'll have to figure out how to convert Geofront's to an ITP then...

I'll be busy with other things for a while, so I'll upload a release with the non-crashing scripts and low-res texture for now.

**Comment by porkbob** [comment] 2022-10-05 15:08
I'll try to remember not to overwrite my saves for these 2 quests, so I can give them a run-through check once you're done.

**Comment by Kyuuhachi** [comment] 2022-10-06 16:58
Alright, both should be properly fixed now. Really, the texture took more work since I had to figure out the whole texture format basically from scratch, whereas including Ken and Nana just took some scripting which I already had good support for.

**Closed as completed by Kyuuhachi** 2022-10-06 16:58 UTC

**Comment by porkbob** [comment] 2022-10-06 17:22
Only the source is in the release? Or will giuthub take time to update?

**Comment by Kyuuhachi** [comment] 2022-10-06 17:47
Oops, I forgot.

**Comment by porkbob** [comment] 2022-10-06 18:41
Looks good. I only saw the tiniest of tiny issues—that being when the lecture is called to attention and everyone gets exclamation bubbles, specifically Ken's lines above his head to show he was talking don't disappear in time and overlap the bubble. I guess the boy in the back row has his text boxes kinda detached from him space-wise too, but you can still tell that's who's speaking.

With that I think we can say, while I may not have tested with absolute complete rigor, it should run within expectation for people who will be generally trying to complete the quests with best DP bonuses. Thanks again!

**Comment by Kyuuhachi** [comment] 2022-10-06 18:43
Yeah, I noticed that too, but I don't think that's something I can do anything about.

Thanks for your help with the testing!
